openapi: 3.0.0
info:
  title: DayPuzzle Backend API
  version: 1.0.0
paths:
  /api/hello:
    get:
      x-google-backend:
        address: https://backend.default.svc.cluster.local
      responses:
        '200':
          description: OK
